### ISSUE TITLE
Website translation in Spanish [COMPLETED]

### ISSUE THREAD

**Issue by vasa-develop** [vyperfun/vyper.fun#15]
**PLEASE REFER TO [CONTRIBUTION GUIDE](https://github.com/vyperfun/vyper.fun/blob/master/CONTRIBUTION.md) TO SEE HOW TO CONTRIBUTE.**

The following **checklist represents the status of the translation of different chapters**. 

The **chapters which are "unchecked" (do NOT have a tick mark) are ready to be translated**. The chapters which is "checked" (have a tick mark) are NOT available for translation.

If you want to translate a chapter(s), you can **COMMENT BELOW with the lesson and chapter numbers**. The chapter(s) will be assigned to you. 

You need to [**raise a Pull Request**](https://hacktoberfest.digitalocean.com/details#beginners) for the translations. After a review, your Pull request will be merged. 

**IF YOU SUBMIT A PULL REQUEST WITHOUT COMMENTING BELOW, YOUR PULL REQUEST WILL NOT BE ACCEPTED.**

### Lesson 1: Your first Pokémon

* [x] [Introduction](https://github.com/vyperfun/vyper.fun/blob/master/es/1/introduction.md)
* [x] [Chapter 1: Contracts](https://github.com/vyperfun/vyper.fun/blob/master/es/1/contract_structure.md)
* [x] [Chapter 2: State Variables, Integers & Constants](https://github.com/vyperfun/vyper.fun/blob/master/es/1/state_vars_and_ints.md)
* [x] [Chapter 3: Math Operations](https://github.com/vyperfun/vyper.fun/blob/master/es/1/math_operations.md)
* [x] [Chapter 4: Structs](https://github.com/vyperfun/vyper.fun/blob/master/es/1/structs.md)
* [x] [Chapter 5: Mappings](https://github.com/vyperfun/vyper.fun/blob/master/es/1/mappings.md)
* [x] [Chapter 6: Function Declarations](https://github.com/vyperfun/vyper.fun/blob/master/es/1/function_declarations.md)
* [x] [Chapter 7: Working With Structs and Mappings](https://github.com/vyperfun/vyper.fun/blob/master/es/1/working_with_structs.md)
* [x] [Chapter 8: External / Internal Functions](https://github.com/vyperfun/vyper.fun/blob/master/es/1/external_internal_functions.md)
* [x] [Chapter 9: Public Variables](https://github.com/vyperfun/vyper.fun/blob/master/es/1/public_vars.md)
* [x] [Chapter 10: More on Functions](https://github.com/vyperfun/vyper.fun/blob/master/es/1/more_on_functions.md)
* [x] [Chapter 11: Keccak256 and Typecasting](https://github.com/vyperfun/vyper.fun/blob/master/es/1/keccak256-and-typecasting.md)
* [x] [Chapter 12: Putting It Together](https://github.com/vyperfun/vyper.fun/blob/master/es/1/putting_it_together.md)
* [x] [Chapter 13: Events](https://github.com/vyperfun/vyper.fun/blob/master/es/1/events.md)

### Lesson 2: Catch'em all

* [x] [Introduction](https://github.com/vyperfun/vyper.fun/blob/master/es/2/introduction.md)
* [x] [Chapter 1: Addresses](https://github.com/vyperfun/vyper.fun/blob/master/es/2/addresses.md)
* [x] [Chapter 2: Msg.sender](https://github.com/vyperfun/vyper.fun/blob/master/es/2/msg-sender.md)
* [x] [Chapter 3: Wild Pokemons](https://github.com/vyperfun/vyper.fun/blob/master/es/2/wild_pokemons.md)
* [x] [Chapter 4: Init Function](https://github.com/vyperfun/vyper.fun/blob/master/es/2/init.md)
* [x] [Chapter 5: Create a Random Wild Pokemon](https://github.com/vyperfun/vyper.fun/blob/master/es/2/random_wild_pokemon.md)
* [x] [Chapter 6: Comparison Operators and If-Else](https://github.com/vyperfun/vyper.fun/blob/master/es/2/comparison_operator.md)
* [x] [Chapter 7: Empty Function](https://github.com/vyperfun/vyper.fun/blob/master/es/2/empty.md)
* [x] [Chapter 8: Interfaces](https://github.com/vyperfun/vyper.fun/blob/master/es/2/interfaces.md)
* [x] [Chapter 9: Assert](https://github.com/vyperfun/vyper.fun/blob/master/es/2/assert.md)
* [x] [Chapter 10: Calling a Contract](https://github.com/vyperfun/vyper.fun/blob/master/es/2/calling_a_contract.md)
* [x] [Chapter 11: Putting it Together](https://github.com/vyperfun/vyper.fun/blob/master/es/2/putting_it_together.md)

**Comment by gzanitti** [comment]
I didn't know you needed help with this. Let's start simple so others can help too: 
"Lesson 1, Introduction"
"Lesson 1, Chapter 1: Contracts"
"Lesson 1, Chapter 2: State Variables, Integers & Constants"
"Lesson 1, Chapter 3: Math Operations"
"Lesson 1, Chapter 4: Structs"
"Lesson 1, Chapter 5: Mappings"

**Comment by gzanitti** [comment]
Ok, considering that there are no new requests, I'm going to continue with five more:
"Lesson 1, Chapter 6: Function Declarations"
"Lesson 1, Chapter 7: Working With Structs and Mappings"
"Lesson 1, Chapter 8: External / Internal Functions"
"Lesson 1, Chapter 9: Public Variables"
"Lesson 1, Chapter 10: More on Functions"

**Comment by Martin-EG** [comment]
Hi, I would like to help
If it's not taken, I'll take Lesson 1 Chapter 11 - 13 to start

**Comment by vasa-develop** [comment]
sure @MarespTech

**Comment by JoseRivera12** [comment]
@vasa-develop I would like help, 
I can translate 
 Introduction
 Chapter 1: Addresses
 Chapter 2: Msg.sender
 Chapter 3: Wild Pokemons
 Chapter 4: Init Function 
if it's not taken

**Comment by toyamarodrigo** [comment]
I will take this four:
 "Chapter 5: Create a Random Wild Pokemon"
 "Chapter 6: Comparison Operators and If-Else"
 "Chapter 7: Empty Function"
 "Chapter 8: Interfaces"

**Comment by h-nick** [comment]
I can help with the remaining three in Lesson 2:

 Chapter 9: Assert
 Chapter 10: Calling a Contract
 Chapter 11: Putting it Together

**Comment by vasa-develop** [comment]
Hi @MarespTech!

Are you still working Lesson 1 Chapter 11 - 13? If yes, let me know here within the next 2 days, otherwise, these chapters will be reassigned to others who want to translate it.

**Comment by Martin-EG** [comment]
Hi,
I still working, tomorrow I think I'll finished
