### ISSUE TITLE
Feedback on the first chapter

### ISSUE THREAD

**Issue by PabloCGL** [vyperfun/vyper.fun#3]
Hi. First of all, great job!
Like I said in the chat, I noticed some small issues while doing chaper 1:
In lesson 10, there is no mention that the function _generateRandomDNA must accept a String[32] as argument, so there is no way to know that the solution expects it.
In lesson 11: In line 4 from the instruction text there is a small typo ("hexidecimal"). The text also claims that converting a negative int128 to uint256 returns the positive counterpart, but the documentation linked states that conversion from a negative int to uint is not allowed. I did a quick test in Remix and the conversion did fail, but maybe I overlooked something and there's a way?

The last one is not so much an issue but a sugggestion: In lesson 9 we create the totalPokemonCount variable and use it to access the pokemonList. While doing it, it feels pretty obvious that we are "forgetting" to increment totalPokemonCount by 1 after creating a Pokemon. We end up adding in that part a couple of lessons later, but while you do the lesson it feels like an oversight from the tutorial. Also, the operator "+=" isn't explained before we use it...
So maybe explain += in lesson 4 together with the other operators, and then in lesson 9 put something like "Remember that += operator we saw before? Let's try it here" , so the function is feels finished (even though we are expanding it later)?

That's all! Anyway. I like what you are doing here a lot and I'd love to contribute. I'm learning Vyper myself, so there's probably not much I can do on the coding side of things, but I'd be glad to proofread, translate (spanish, german), or just be the first user  :)

**Comment by vasa-develop** [comment]
@PabloCGL A big thank you for these great suggestions. I will update these ASAP.
Also, I'll add the instructions to contribute translations in a day or two :)

**UPDATE:** I have updated the chapters as per your suggestions.
